/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#4143d5',
        'primary-container': '#5b5fef',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#f9f6ff',
        'on-primary-fixed': '#05006c',
        'on-primary-fixed-variant': '#2c2cc3',

        'secondary': '#5846c8',
        'secondary-container': '#7161e3',
        'secondary-fixed': '#e4dfff',
        'secondary-fixed-dim': '#c7bfff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'on-secondary-fixed': '#170065',
        'on-secondary-fixed-variant': '#422db2',

        'tertiary': '#a62a30',
        'tertiary-container': '#c84245',
        'tertiary-fixed': '#ffdad8',
        'tertiary-fixed-dim': '#ffb3b0',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fff5f4',
        'on-tertiary-fixed': '#410006',
        'on-tertiary-fixed-variant': '#8c1520',

        'surface': '#fcf8ff',
        'surface-dim': '#dad7f3',
        'surface-bright': '#fcf8ff',
        'surface-variant': '#e2e0fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'surface-container': '#efecff',
        'surface-container-high': '#e8e5ff',
        'surface-container-highest': '#e2e0fc',
        'surface-tint': '#474adb',
        'on-surface': '#1a1a2e',
        'on-surface-variant': '#464555',
        'inverse-surface': '#2f2e43',
        'inverse-on-surface': '#f2efff',
        'inverse-primary': '#c0c1ff',
        'background': '#fcf8ff',
        'on-background': '#1a1a2e',

        'outline': '#767586',
        'outline-variant': '#c6c5d7',

        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',

        'emerald-online': '#34D399',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'micro-timestamp': ['Inter', 'sans-serif'],
        'title-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-md-medium': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'micro-timestamp': ['10px', { lineHeight: '12px', letterSpacing: '0.025em', fontWeight: '500' }],
        'title-sm': ['16px', { lineHeight: '22px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md-medium': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
      },
      spacing: {
        'space-2xl': '2rem',
        'space-sm': '0.5rem',
        'space-2xs': '0.125rem',
        'space-base': '1rem',
        'space-xl': '1.5rem',
        'space-lg': '1.25rem',
        'space-md': '0.75rem',
        'gutter': '1rem',
        'margin-mobile': '1rem',
        'margin': '1.25rem',
        'space-xs': '0.25rem',
        'gutter-mobile': '0.75rem',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}

